<div class="header-container">
    <div class="header">
        <div class="container">
            <div id="logo" onclick="window.location.href='homePage.php'">
                <div class="imgholder">
                    <img class="img" src="images/park_logo.png" alt="Park logo">
                </div>
            </div>
            <ul class="nav">
                <li><a href="homePage.php#GoogleMap">Nearby Parks</a></li>
                <li><a href="homePage.php#featuredParks">Featured Parks</a></li>
                <li><a href="aboutUs.php">About</a></li>
                <!-- Button on front page to open signup popup form -->
                <li><button onclick="window.location.href='SignUp.php'" class="signupopt">Sign Up</button>
                    <button onclick="window.location.href='Login.php'" class="loginopt">Login</button></li>
            </ul>
        </div>
    </div>
</div>
